'use client'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import * as Icons from 'lucide-react'
import { useState } from 'react'

const questions = [
  { id: 1, question: "What do convolutional layers in CNNs do?", options: ["Detect local features like edges and textures", "Classify images directly", "Reduce image size", "Encode pixel colors"], correct: 0, explanation: "Convolutional layers slide filters across images to detect features at different positions and scales." },
  { id: 2, question: "Why is transfer learning powerful for computer vision?", options: ["Pre-trained models learn general features that transfer across tasks", "It's the fastest training method", "It eliminates the need for data", "It prevents overfitting completely"], correct: 0, explanation: "Models trained on large datasets learn generalizable features that work well when fine-tuned on smaller datasets." },
  { id: 3, question: "What is object detection?", options: ["Finding objects and their bounding boxes in images", "Classifying objects into categories", "Describing images in text", "Counting pixels"], correct: 0, explanation: "Object detection identifies locations and bounds of multiple objects in an image, unlike classification which labels the whole image." },
  { id: 4, question: "How do pooling layers help CNNs?", options: ["They downsample feature maps and make models more efficient", "They increase the image size", "They apply convolutions multiple times", "They add more trainable parameters"], correct: 0, explanation: "Pooling reduces dimensionality, improves computational efficiency, and provides translation invariance." },
  { id: 5, question: "What is semantic segmentation?", options: ["Classifying every pixel in an image", "Drawing bounding boxes around objects", "Detecting object centers", "Counting distinct objects"], correct: 0, explanation: "Semantic segmentation assigns a class label to every pixel, creating a dense prediction map." }
]

export function CVQuiz() {
  const [current, setCurrent] = useState(0), [selected, setSelected] = useState<number | null>(null), [show, setShow] = useState(false), [score, setScore] = useState(0), [done, setDone] = useState(false)
  const q = questions[current]
  return done ? (
    <Card className="bg-gradient-to-r from-purple-600/10 to-purple-600/10"><CardHeader><CardTitle className="flex items-center gap-2"><Icons.Trophy className="w-5 h-5" />Complete!</CardTitle></CardHeader><CardContent className="space-y-4"><div className="text-center"><div className="text-5xl font-bold">{Math.round((score/5)*100)}%</div><p className="text-muted-foreground">{score}/5 correct</p>{score>=4 && <p className="text-green-600 font-semibold">Excellent!</p>}</div><Button onClick={()=>{setCurrent(0);setSelected(null);setShow(false);setScore(0);setDone(false)}} className="w-full"><Icons.RotateCcw className="w-4 h-4 mr-2" />Retake</Button></CardContent></Card>
  ) : (
    <Card className="bg-gradient-to-r from-purple-600/10 to-purple-600/10"><CardHeader><CardTitle className="flex items-center gap-2"><Icons.Brain className="w-5 h-5" />Test Your Knowledge</CardTitle></CardHeader><CardContent className="space-y-6"><div className="flex justify-between text-sm text-muted-foreground">Q {current+1}/{questions.length}</div><h3 className="font-semibold text-lg">{q.question}</h3><div className="space-y-3">{q.options.map((opt, i)=><button key={i} onClick={()=>!show&&setSelected(i)} className={`w-full p-3 rounded-lg border-2 text-left ${selected===i?i===q.correct&&show?'border-green-500 bg-green-500/10':'border-red-500 bg-red-500/10':show&&i===q.correct?'border-green-500 bg-green-500/10':'border-muted hover:border-primary/50'} ${show?'cursor-default':'cursor-pointer'}`} disabled={show}><div className="flex items-center gap-2"><div className={`w-5 h-5 rounded-full border-2 ${selected===i?'border-primary':'border-muted-foreground'}`}>{selected===i&&<div className="w-3 h-3 rounded-full bg-primary m-auto" />}</div><span>{opt}</span>{show&&i===q.correct&&<Icons.Check className="ml-auto text-green-600 w-5 h-5" />}{show&&selected===i&&i!==q.correct&&<Icons.X className="ml-auto text-red-600 w-5 h-5" />}</div></button>)}</div>{show&&<div className="bg-blue-500/10 border border-blue-500/20 rounded-lg p-4"><p className="text-sm"><strong>Explanation:</strong> {q.explanation}</p></div>}{!show?<Button onClick={()=>{if(selected!==null){if(selected===q.correct)setScore(score+1);setShow(true)}}} className="w-full" disabled={selected===null}>Submit</Button>:<Button onClick={()=>{if(current<4){setCurrent(current+1);setSelected(null);setShow(false)}else setDone(true)}} className="w-full">{current===4?'See Results':'Next'}</Button>}</CardContent></Card>
  )
}
